# Generated by Django 6.1.1 on 2026-09-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='pin_code',
            field=models.IntegerField(),
        ),
    ]
