# Generated by Django 6.1.1 on 2026-09-22 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0002_alter_station_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabs',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='cabs.station'),
        ),
        migrations.AlterField(
            model_name='cabs',
            name='pick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deparutres', to='cabs.station'),
        ),
    ]
