# Generated by Django 6.1.1 on 2026-09-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0003_alter_cabs_drop_alter_cabs_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabs',
            name='pick',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='cabs.station'),
        ),
    ]
