# Generated by Django 6.1.1 on 2026-09-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0004_alter_cabs_pick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('cabs', models.ManyToManyField(blank=True, related_name='passangers', to='cabs.cabs')),
            ],
        ),
    ]
